// Package updater keeps the skills CLI current by fast-forwarding the git
// checkout the binary lives in and rebuilding it in place. It intentionally
// does no network work beyond git fetch, and never discards the user's own
// uncommitted changes.
package updater

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"strconv"
	"strings"
	"time"
)

// buildArtifacts are tracked files regenerated by a build. They are routinely
// dirty in a working tree that has run `make build`, and are safe to discard
// before a fast-forward because the update rebuilds them anyway.
var buildArtifacts = []string{"cli/skills", "cli/skills-cli"}

// Result describes what an Update did.
type Result struct {
	Branch    string
	OldCommit string
	NewCommit string
	Pulled    bool // fast-forwarded to new upstream commits
	Rebuilt   bool // the binary was recompiled
}

func git(repoDir string, args ...string) (string, error) {
	cmd := exec.Command("git", append([]string{"-C", repoDir}, args...)...)
	var out, errb bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errb
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(errb.String())
		if msg == "" {
			msg = err.Error()
		}
		return "", fmt.Errorf("git %s: %s", strings.Join(args, " "), msg)
	}
	return strings.TrimSpace(out.String()), nil
}

// IsRepo reports whether repoDir is inside a git work tree.
func IsRepo(repoDir string) bool {
	out, err := git(repoDir, "rev-parse", "--is-inside-work-tree")
	return err == nil && out == "true"
}

// ShortHead returns the abbreviated HEAD commit.
func ShortHead(repoDir string) (string, error) {
	return git(repoDir, "rev-parse", "--short", "HEAD")
}

// CurrentBranch returns the checked-out branch name (or "HEAD" if detached).
func CurrentBranch(repoDir string) (string, error) {
	return git(repoDir, "rev-parse", "--abbrev-ref", "HEAD")
}

// DirtyTrackedFiles lists modified tracked files (staged and unstaged),
// excluding untracked files and build artifacts. A non-empty result means the
// user has real local changes that a fast-forward must not clobber.
func DirtyTrackedFiles(repoDir string) ([]string, error) {
	seen := map[string]bool{}
	var dirty []string
	for _, args := range [][]string{
		{"diff", "--name-only"},             // unstaged changes to tracked files
		{"diff", "--name-only", "--cached"}, // staged changes
	} {
		out, err := git(repoDir, args...)
		if err != nil {
			return nil, err
		}
		for line := range strings.SplitSeq(out, "\n") {
			path := strings.TrimSpace(line)
			if path == "" || isArtifact(path) || seen[path] {
				continue
			}
			seen[path] = true
			dirty = append(dirty, path)
		}
	}
	return dirty, nil
}

func isArtifact(path string) bool {
	return slices.Contains(buildArtifacts, path)
}

// discardArtifacts restores any dirty build artifact so a fast-forward is not
// blocked by the locally-built binary. Only the artifact paths are touched.
func discardArtifacts(repoDir string) {
	for _, a := range buildArtifacts {
		if _, err := os.Stat(filepath.Join(repoDir, a)); err == nil {
			_, _ = git(repoDir, "checkout", "--", a)
		}
	}
}

// Fetch updates remote-tracking refs, bounded by timeout. Best-effort.
func Fetch(repoDir string, timeout time.Duration) error {
	ctx, cancel := context.WithTimeout(context.Background(), timeout)
	defer cancel()
	return exec.CommandContext(ctx, "git", "-C", repoDir, "fetch", "--quiet").Run()
}

// Upstream returns the current branch's upstream ref (e.g. origin/main).
func Upstream(repoDir string) (string, error) {
	up, err := git(repoDir, "rev-parse", "--abbrev-ref", "--symbolic-full-name", "@{u}")
	if err != nil {
		return "", fmt.Errorf("no upstream is configured for the current branch")
	}
	return up, nil
}

// Divergence reports how many commits HEAD is ahead of and behind its upstream.
func Divergence(repoDir string) (ahead, behind int, upstream string, err error) {
	upstream, err = Upstream(repoDir)
	if err != nil {
		return 0, 0, "", err
	}
	out, err := git(repoDir, "rev-list", "--left-right", "--count", "HEAD..."+upstream)
	if err != nil {
		return 0, 0, upstream, err
	}
	fields := strings.Fields(out)
	if len(fields) != 2 {
		return 0, 0, upstream, fmt.Errorf("unexpected rev-list output: %q", out)
	}
	ahead, _ = strconv.Atoi(fields[0])
	behind, _ = strconv.Atoi(fields[1])
	return ahead, behind, upstream, nil
}

// Rebuild recompiles the CLI into cli/skills, stamping the current HEAD as the
// build commit. It builds to a temp file and renames it into place so replacing
// the currently-running binary is atomic and safe.
func Rebuild(repoDir string) (string, error) {
	head, err := ShortHead(repoDir)
	if err != nil {
		return "", err
	}
	cliDir := filepath.Join(repoDir, "cli")
	tmp, err := os.CreateTemp(cliDir, ".skills-build-*")
	if err != nil {
		return "", fmt.Errorf("creating temp build file: %w", err)
	}
	tmpPath := tmp.Name()
	tmp.Close()

	cmd := exec.Command("go", "build",
		"-ldflags", "-X main.buildCommit="+head,
		"-o", tmpPath, "./cmd/skills")
	cmd.Dir = cliDir
	cmd.Env = append(os.Environ(), "CGO_ENABLED=0")
	var errb bytes.Buffer
	cmd.Stderr = &errb
	if err := cmd.Run(); err != nil {
		os.Remove(tmpPath)
		msg := strings.TrimSpace(errb.String())
		if msg == "" {
			msg = err.Error()
		}
		return "", fmt.Errorf("go build failed: %s", msg)
	}
	if err := os.Chmod(tmpPath, 0o755); err != nil {
		os.Remove(tmpPath)
		return "", err
	}
	if err := os.Rename(tmpPath, filepath.Join(cliDir, "skills")); err != nil {
		os.Remove(tmpPath)
		return "", fmt.Errorf("replacing binary: %w", err)
	}
	return head, nil
}

// Update fast-forwards the checkout and rebuilds the binary. currentBuild is the
// commit the running binary was built from, used to skip a no-op rebuild.
// Progress is written to w. It never discards the user's uncommitted changes.
func Update(repoDir, currentBuild string, w io.Writer) (Result, error) {
	var res Result
	if !IsRepo(repoDir) {
		return res, fmt.Errorf("%s is not a git checkout; auto-update needs a git clone of the skills repo", repoDir)
	}
	if _, err := exec.LookPath("git"); err != nil {
		return res, fmt.Errorf("git is not on PATH")
	}
	if _, err := exec.LookPath("go"); err != nil {
		return res, fmt.Errorf("the Go toolchain is not on PATH (needed to rebuild the binary)")
	}

	res.Branch, _ = CurrentBranch(repoDir)
	res.OldCommit, _ = ShortHead(repoDir)

	dirty, err := DirtyTrackedFiles(repoDir)
	if err != nil {
		return res, err
	}
	if len(dirty) > 0 {
		return res, fmt.Errorf("you have uncommitted changes (%s); commit or stash them before updating", strings.Join(dirty, ", "))
	}
	discardArtifacts(repoDir)

	fmt.Fprintln(w, "Fetching updates ...")
	if err := Fetch(repoDir, 30*time.Second); err != nil {
		return res, fmt.Errorf("git fetch failed: %w", err)
	}

	ahead, behind, upstream, err := Divergence(repoDir)
	if err != nil {
		return res, err
	}
	if ahead > 0 {
		return res, fmt.Errorf("branch %q has %d local commit(s) not on %s; update won't fast-forward — reconcile manually", res.Branch, ahead, upstream)
	}
	if behind > 0 {
		fmt.Fprintf(w, "Fast-forwarding %s by %d commit(s) from %s ...\n", res.Branch, behind, upstream)
		if _, err := git(repoDir, "merge", "--ff-only", upstream); err != nil {
			return res, fmt.Errorf("fast-forward failed: %w", err)
		}
		res.Pulled = true
	}

	newHead, err := ShortHead(repoDir)
	if err != nil {
		return res, err
	}
	if !res.Pulled && newHead == currentBuild {
		fmt.Fprintln(w, "Already up to date.")
		res.NewCommit = newHead
		return res, nil
	}

	fmt.Fprintln(w, "Rebuilding ...")
	built, err := Rebuild(repoDir)
	if err != nil {
		return res, err
	}
	res.NewCommit = built
	res.Rebuilt = true
	return res, nil
}
