#!/usr/bin/env node
/**
 * scaffold_scores.mjs — print the scores.tsv skeleton for an A/B family run.
 *
 * Fills in every expected case x arm x rep row so the eval harness writes into
 * the right cells, and the report is one `score_ab.py` pass away. Generic over
 * any `*_pilot_cases.json`.
 *
 * Blank scores are left for the harness: `score_ab.py` skips rows whose score
 * is still blank (it treats empty / `_` / `na` as "not yet scored"). C-substitute
 * rows are commented out because arm C runs only on cases where mean(A) - mean(B)
 * > 0.15; uncomment (remove the leading `#`) a case's C rows if arm C ran.
 *
 * Usage:
 *   node scripts/scaffold_scores.mjs --cases evals/ui_family_cases.json > scores.tsv
 *   node scripts/scaffold_scores.mjs --cases <file> --reps 3 --run wf_xxxx
 */
import { readFileSync } from 'node:fs';

const arg = (n, d = null) => {
  const i = process.argv.indexOf(n);
  return i >= 0 ? process.argv[i + 1] : d;
};
const casesPath = arg('--cases', 'evals/ui_family_cases.json');
const reps = parseInt(arg('--reps', '3'), 10);
const runId = arg('--run', '<wf_run_id>');

const spec = JSON.parse(readFileSync(casesPath, 'utf8'));
const arms = Object.keys(spec.arms);
const armLetter = Object.fromEntries(arms.map((a) => [a, /^([A-Za-z])_/.exec(a)?.[1] ?? a[0]]));
const order = arms.filter((a) => armLetter[a] !== 'C');
const cArm = arms.find((a) => armLetter[a] === 'C');

const out = [];
out.push(`# ui/knowledge-quality A/B scores (generated by scaffold_scores.mjs from ${casesPath})`);
out.push(`# Save this as scores.tsv next to the eval journal, then fill <score> (0-1) and, when you have them,`);
out.push(`#    the ${5}th column <avoid_violations> (count of must_exclude present). Columns: case  arm  rep  score  [avoid]`);
out.push(`# Verify with:  python3 scripts/score_ab.py ${casesPath} scores.tsv`);
out.push(`# Report:       cp evals/results/TEMPLATE-ui-family.md evals/results/<date>-ui-family.md`);
out.push(`# Run id: ${runId}`);
out.push('');
for (const a of order) {
  for (let r = 1; r <= reps; r++) {
    for (const c of spec.cases) out.push(`${c.id}\t${armLetter[a]}\t${r}\t`);
  }
}
if (cArm) {
  out.push('');
  out.push(`# Arm C (${armLetter[cArm]}) rows — comment-in (drop the leading '#') only for cases where arm C ran:`);
  for (let r = 1; r <= reps; r++) {
    for (const c of spec.cases) out.push(`#${c.id}\t${armLetter[cArm]}\t${r}\t`);
  }
}

process.stdout.write(out.join('\n') + '\n');